name: CI

on:
  push:
    branches:
      - master

jobs:
  build-push:
    uses: jportasa/ci-reusable-library/.github/workflows/ci.yaml@master
    with:
      image: jportacloud/golang-equisens-bitly
      environment: development
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

