name: CI

on:
  push:
    branches:
      - master

jobs:
  build-push:
    uses: jportasa/ci-reusable-library/.github/workflows/ci.yaml@main
    with:
      image: production,staging
      environment: development
